CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT( ID INT PRIMARY KEY,NAME VARCHAR(20),AGE INT NOT NULL);
INSERT INTO STUDENT VALUE(5,"KARAN",21),(6,"ANIL",23);


SELECT * FROM STUDENT;
SHOW DATABASES;
SHOW TABLES;
CREATE DATABASE GOOGLE;
USE GOOGLE;
CREATE TABLE EMPLOYEE(ID INT PRIMARY KEY,NAME VARCHAR (20),SALARY INT);
INSERT INTO EMPLOYEE VALUE(1,"ADAM",25000),(2,"BOB",30000),(3,"CASEY",40000);
CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE student(ROLLNO INT PRIMARY KEY,
					NAME VARCHAR (20),
                    MARKS INT NOT NULL,
                    GRADE VARCHAR (5),
                    CITY VARCHAR (20));
INSERT INTO student
(ROLLNO,NAME,MARKS,GRADE,CITY) 
VALUE 
(101,"ANIL",78,"C","PUNE"),
(102,"BHUMIKA",93,"A","MUMBAI"),
(103,"CHETAN",85,"B","MUMBAI"),
(104,"DHURV",96,"A","DELHI"),
(105,"EMANUEL",12,"F","DELHI"),
(106,"FARAH",82,"B","DELHI");


SELECT NAME, MARKS FROM student;
SELECT CITY FROM student;
SELECT DISTINCT CITY FROM student;
SELECT * FROM student WHERE MARKS > 80;
SELECT * FROM student WHERE CITY = "MUMBAI";
SELECT * FROM student WHERE MARKS > 80 AND CITY= "MUMBAI";
SELECT * FROM student WHERE MARKS > 80 OR CITY= "MUMBAI";
SELECT * FROM student WHERE MARKS BETWEEN 80 AND 90;
SELECT * FROM student WHERE CITY IN("DELHI","MUMBAI");
SELECT * FROM student WHERE CITY NOT IN("DELHI","MUMBAI");
SELECT * FROM student LIMIT 3;
SELECT * FROM student WHERE MARKS >75 LIMIT 3;
SELECT * FROM student ORDER BY CITY ASC;
SELECT * FROM student ORDER BY MARKS ASC;
SELECT * FROM student ORDER BY MARKS DESC LIMIT 2;
ALTER TABLE student ADD STATUS VARCHAR (10) DEFAULT ("ACTIVE");

SELECT * FROM student;
ALTER TABLE student ADD CONSTRAINT UNIQUE (NAME);
ALTER TABLE student DROP CONSTRAINT UNIQUE_NAME;
ALTER TABLE STUDENT MODIFY ID INT auto_increment;
INSERT INTO student
(NAME,MARKS,GRADE,CITY) 
VALUE 
("ANIL",78,"C","PUNE");
ALTER TABLE STUDENT ADD MARKS INT;
SELECT * FROM STUDENT;
SELECT SUM(MARKS)AS TOTAL_MARKS FROM STUDENT;
SELECT AVG(MARKS)AS TOTAL_MARKS FROM STUDENT;
