SHOW DATABASES;
CREATE DATABASE STUDENTRECORD;
USE STUDENTRECORD;

CREATE TABLE STUDENTDETAILS( ROLLNO INT PRIMARY KEY,
							NAME VARCHAR(20) NOT NULL,
                            GENDER VARCHAR(1),
                            AGE INT NOT NULL,
                            COURSE VARCHAR(20),
                            SEMSTER INT,
                            CONTACT VARCHAR(12) NOT NULL);

INSERT INTO STUDENTDETAILS (ROLLNO,STUDENTNAME,GENDER,AGE,COURSE,SEMSTER,CONTACT) values(7,"PREETI","F",22,"DATA SCIENCE",4,"92345418529");
SHOW tables;
select*FROM STUDENTDETAILS;


SELECT * FROM STUDENTDETAILS WHERE AGE >24;
SELECT * FROM STUDENTDETAILS WHERE AGE <24;
SELECT * FROM STUDENTDETAILS WHERE AGE =21;
SELECT * FROM STUDENTDETAILS WHERE AGE >=21;
SELECT * FROM STUDENTDETAILS WHERE AGE <=23;
SELECT * FROM STUDENTDETAILS WHERE AGE >23 AND SEMSTER=4;



delete from  STUDENTDETAILS;
SELECT * FROM STUDENTDEATAILS ORDER BY STUDENTNAME DESC;

CREATE DATABASE INVENTORY;
USE INVENTORY;
CREATE TABLE INVENTORYDETAILS(SN INT PRIMARY KEY,
							ITEMNAME VARCHAR(20),
                            TOTALPURCHASE INT(4),
                            PRICEPERUNIT INT(10),
                            TOTALSALE INT(20)NOT NULL,
                            STOCKSAVAILABLE INT(5)NOT NULL);